export const SEARCH_SUGGESTIONS = [
	'Socks',
	'Toys',
	'Guitar',
	'Piano',
	'Clothing',
	'Pencils',
	'Books',
	'Paper',
	'Phone',
	'Laptop',
	'Calculator',
	'Marker',
	'Laptop case',
	'Phone case',
	'Glasses',
	'Bicycle',
	'Coffee filter',
	'Keyboard',
	'Computer mouse',
	'Makeup',
	'Shoes',
	'All-purpose cleaner',
	'Disinfecting wipes',
	'Window cleaner',
	'hand duster',
	'detail brush',
	'scrub brush',
	'cleaning cloth',
	'utility belt',
	'storage caddy',
	'vacuum',
	'broom and dustpan',
	'mop',
	'Rubber gloves ',
	'plunger',
	'toilet brush ',
	'bucket',
	'Bath towels',
	'Hand towels',
	'bed sheets',
	'blanket',
	'comforter',
	'bathmat',
	'flower vase',
	'Coasters',
	'Window treatments ',
	'clock ',
	'mirror',
	'lamp',
	'Smoke alarm ',
	'candles',
	'Matches',
	'First-aid kit',
	'Band-aids',
	'Gauze',
	'flashlight',
	'phone charger',
	'fire extinguisher',
	'umbrella',
	'Bottled water',
	'Canned food',
	'Batteries',
];

